### ISSUE TITLE
Failed to upload file

### ISSUE THREAD

**Issue by boundless-forest** [PinataCloud/pinata#25]
I'm working on a script (pasted below) to upload the NFT image and metadata. It seems the API is not stable; I have succeeded several times, but most of the time it reports this error, and I have no idea about the solution.

```js
async function generateTokenUrl(text, tokenId) {
  // Generate token image and save it to disk
  let tokenName = text.concat(tokenId.toString());
  let tokenPath = "./tokens/" + tokenName + ".png";
  let imageBuffer = createImage(tokenName);
  fs.writeFileSync(tokenPath, imageBuffer);

  // Upload image to Pinata
  let image = fs.readFileSync(tokenPath);
  let blob = new Blob([image]);
  let file = new File([blob], tokenName, { type: "image/png" });
  let imageUploadResponse = await pinata.upload.file(file);
  console.log("imageUploadResponse: ", imageUploadResponse);

  // Create metadata and save it to disk
  let metadata = {
    name: "Lesson " + tokenId + " NFT",
    description: "This is the Darwinia Bootcamp Lesson " + tokenId + " NFT",
    image: "ipfs://" + imageUploadResponse.cid,
    external_url: "https://pinata.cloud",
  };
  let metadataPath = "./tokens/" + tokenName + ".json";
  fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));

  // Upload metadata to Pinata
  let metadataUploadResponse = await pinata.upload.json(metadata);
  console.log("metadataUploadResponse: ", metadataUploadResponse);

  // Return token metadata URL
  return "ipfs://" + metadataUploadResponse.cid;
}
```

The error report:

```sh
PinataError: Error uploading file: fetch failed
    at UploadBuilder.uploadFile [as uploadFunction] (/mnt/myssd/coding/darwinia-space/bootcamp-examples/erc721/node_modules/pinata/dist/index.js:163:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateTokenUrl (/mnt/myssd/coding/darwinia-space/bootcamp-examples/erc721/scripts/token_url.js:41:29)
    at async testing (/mnt/myssd/coding/darwinia-space/bootcamp-examples/erc721/scripts/play.js:29:17) {
  statusCode: undefined,
  details: undefined

```

**Comment by boundless-forest** [comment]
Adding a retry makes it work; feel free to close it.

**Comment by stevedylandev** [comment]
Hey there! This is likely due to this SDK's most recent breaking change. If you are trying to use Pinata for IPFS and NFTs please try [`pinata-web3`](https://github.com/PinataCloud/pinata-web3).
